rabbit:
  host: "localhost"
  port: "5672"
  username: "guest"
  password: "guest"

postgres:
  username: "dev"
  host: "localhost"
  password: "gc135"
  port: "5432"
  dbname: "storage"
  retry: 10
  timeWaitPerTry : 3000000000

gateway:
  port: "8080"
  host: "localhost"
  path: "response"