rabbit:
  host: "localhost"
  port: "5672"
  username: "guest"
  password: "guest"

postgres:
  username: "postgres"
#  username: "dev"
#  host: "408e610aba86"
  host: "localhost"
  password: "password"
#    password: "gc135"
  port: "5432"
  dbname: "database"
  retry: 10
  timeWaitPerTry : 3000000000

gateway:
  port: "8080"
  host: "localhost"
  path: "response"