rabbit:
  host: "localhost"
  port: "5672"
  username: "guest"
  password: "guest"

postgres:
  username: "postgres"
  host: "postgres"
  #host: "localhost"
  port: "3306" #"3309"
  dbname: "postgres"
  retry: 10
  timeWaitPerTry : 3000000000 #3s